service: twitter-auth

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev.yml)}
#      prd: ${file(./conf/prd.yml)}

functions:
  auth_twitter:
    handler: src/functions/auth/twitter.auth
    environment:
      TWITTER_CONSUMER_KEY: ${self:custom.otherfile.environment.${self:provider.stage}.TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.TWITTER_CONSUMER_SECRET}
    events:
      - http:
          path: auth
          method: get

  auth_callback:
    handler: src/functions/auth/twitter.callback
    environment:
      TWITTER_CONSUMER_KEY: ${self:custom.otherfile.environment.${self:provider.stage}.TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${self:custom.otherfile.environment.${self:provider.stage}.TWITTER_CONSUMER_SECRET}
      TWITTER_CLIENT_REDIRECT_URL: ${self:custom.otherfile.environment.${self:provider.stage}.TWITTER_CLIENT_REDIRECT_URL}
    events:
      - http:
          path: auth/callback
          method: get


  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: aws_iam
